----------------------------------陈冕部分---------------------------------------
---管理员
INSERT INTO PARK_ADMIN VALUES(1, 1, 'zhangsan', '123', 1, '', SYSDATE, SYSDATE);
INSERT INTO PARK_ADMIN VALUES(2, 1, 'lisi', '123', 1, '', SYSDATE, SYSDATE);
--日志
INSERT INTO PARK_LOG VALUES(1, 1,'登录', 1, '',  SYSDATE);
INSERT INTO PARK_LOG VALUES(2, 1,'注册', 1, '',  SYSDATE);
INSERT INTO PARK_LOG VALUES(3, 1,'收费', 1, '',  SYSDATE);
INSERT INTO PARK_LOG VALUES(4, 1,'办卡', 1, '',  SYSDATE);
INSERT INTO PARK_LOG VALUES(5, 2,'退款', 1, '',  SYSDATE);
INSERT INTO PARK_LOG VALUES(6, 2,'收费', 1, '',  SYSDATE);
INSERT INTO PARK_LOG VALUES(7, 2,'续卡', 1, '',  SYSDATE);
INSERT INTO PARK_LOG VALUES(8, 2,'退款', 1, '',  SYSDATE);
--人工收费信息
INSERT INTO PARK_AMOUNT_LOG VALUES(1, 1, '闽A570W3',0,  '15分',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(2, 1, '闽A77777',10, '1小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(3, 1, '闽K50707',15, '2小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(4, 1, '闽K88888',20, '3小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(5, 2, '闽CH8E62',30, '4小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(6, 2, '闽C66666',40, '5小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(7, 2, '京A22222',50, '6小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(8, 2, '苏A33333',80, '9小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(9, 1, '浙A22222',50, '8小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(10, 1, '豫A55555',40, '7小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(11, 2, '沪A88888',30, '6小时',1,'', SYSDATE);
INSERT INTO PARK_AMOUNT_LOG VALUES(12, 2, '广A11111',20, '5小时',1,'', SYSDATE);
--自助收费信息
INSERT INTO PARK_MACHINE_LOG VALUES(1, 1, '广A11111',20, '3小时',1,'', SYSDATE);
INSERT INTO PARK_MACHINE_LOG VALUES(2, 2, '沪A88888',30, '4小时',1,'', SYSDATE);
INSERT INTO PARK_MACHINE_LOG VALUES(3, 3, '豫A55555',40, '5小时',1,'', SYSDATE);
INSERT INTO PARK_MACHINE_LOG VALUES(4, 4, '浙A22222',50, '6小时',1,'', SYSDATE);
INSERT INTO PARK_MACHINE_LOG VALUES(5, 1, '苏A33333',40, '5小时',1,'', SYSDATE);
INSERT INTO PARK_MACHINE_LOG VALUES(6, 2, '京A22222',30, '4小时',1,'', SYSDATE);
INSERT INTO PARK_MACHINE_LOG VALUES(7, 3, '闽C66666',20, '3小时',1,'', SYSDATE);
INSERT INTO PARK_MACHINE_LOG VALUES(8, 4, '闽CH8E62',15, '2小时',1,'', SYSDATE);
--车辆信息
INSERT INTO PARK_CARNUM VALUES(1, 1, '闽A570W3','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(2, 2, '闽A77777','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(3, 1, '闽K50707','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(4, 2, '闽K88888','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(5, 1, '闽CH8E62','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(6, 2, '闽C66666','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(7, 1, '京A22222','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(8, 2, '苏A33333','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(9, 1, '浙A22222','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(10, 2, '豫A55555','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(11, 1, '沪A88888','url', 1,'', SYSDATE, SYSDATE);
INSERT INTO PARK_CARNUM VALUES(12, 2, '广A11111','url', 1,'', SYSDATE, SYSDATE);
--车辆角色
INSERT INTO PARK_CAR_ROLE VALUES(1, '临时用户', 1 , '' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_ROLE VALUES(2, '月卡用户', 1 , '' , SYSDATE, SYSDATE);
--车辆服务
INSERT INTO PARK_CAR_SERVICE VALUES(1, 1,  101 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(2, 2,  102 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(3, 3,  103 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(4, 4,  104 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(5, 5,  101 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(6, 6,  102 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(7, 7,  103 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(8, 8,  104 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(9, 9,  101 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(10, 10,  102 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(11, 11,  103 , 1 ,'' , SYSDATE, SYSDATE);
INSERT INTO PARK_CAR_SERVICE VALUES(12, 12,  104 , 1 ,'' , SYSDATE, SYSDATE);

------------------------------------------------------------------------------