
INSERT INTO PARK_MENU VALUES (1,0,'用户管理','null',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (5,1,'角色配置','roleManager',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (6,1,'用户配置','adminRole',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (7,1,'用户配置','whiteList',1,null,SYSDATE,SYSDATE);

INSERT INTO PARK_MENU VALUES (2,0,'配置查看管理','null',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (8,2,'计费规则','feeRule',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (9,2,'收支明细','amountLog',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (10,2,'班次日结算','dailyAccount',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (11,2,'自动日结算','dayCount',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (12,2,'月缴产品配置','monthProduct',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (13,2,'月缴产品显示','sellMonthProduct',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (14,2,'菜单管理','menuManager',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (15,2,'配置','configure',1,null,SYSDATE,SYSDATE);


INSERT INTO PARK_MENU VALUES (3,0,'分类统计','income',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (16,3,'总收入、总停车数和统计','null',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (17,3,'临时、月缴用户明细和统计','incomeMonth',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (18,3,'月缴产品明细和统计','incomeProduct',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (19,3,'自助终端统计','incomeMechine',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (20,3,'人工收费统计','incomeManual',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (21,3,'渠道统计','incomeChannel',1,null,SYSDATE,SYSDATE);

INSERT INTO PARK_MENU VALUES (4,0,'日志查看','null',1,null,SYSDATE,SYSDATE);
INSERT INTO PARK_MENU VALUES (22,4,'日志','log',1,null,SYSDATE,SYSDATE);

COMMIT;
